sonar.projectKey=Kosuuuu_BudgetApp
sonar.organization=kosuuuu
sonar.host.url=https://sonarcloud.io

sonar.modules=backend,frontend

backend.sonar.projectBaseDir=backend
backend.sonar.sources=src/main
backend.sonar.tests=src/test
backend.sonar.java.binaries=target/classes

frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/*.test.tsx,**/__tests__/**,node_modules/**,dist/**